name: ascript-lab

services:
  speechtotext:
    container_name: ascript-lab-speechtotext
    deploy:
      resources:
        limits:
          memory: "8G"
    environment:
      eula: accept
      Billing: ${ENDPOINT_URL}
      ApiKey: ${API_KEY}
    networks:
      - ascript-lab
    image: mcr.microsoft.com/azure-cognitive-services/speechservices/speech-to-text:latest
    ports:
      - "5000:5000"
  speechcli:
    container_name: ascript-lab-speechcli
    entrypoint: /bin/bash
    image: msftspeech/spx
    networks:
      - ascript-lab
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: ../data/intermediate
        target: /intermediate
      - type: volume
        source: ascript-lab-speechclidata
        target: /data

networks:
  ascript-lab:

volumes:
  ascript-lab-speechclidata:
